-- Crear tablas para el sistema de lista de interés de souvenirs

-- Tabla principal de solicitudes de interés
create table if not exists public.interest_requests(
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  status text not null default 'received'
    check(status in('received','priced','sent_to_client','closed_won','closed_lost')),
  requester_name text not null,
  organization text,
  email text,
  phone text,
  notes text,
  source text not null default 'souvenirs',
  locale text not null default 'es',
  channel text not null default 'web',
  admin_notes text
);

-- Tabla de items de solicitudes de interés
create table if not exists public.interest_request_items(
  id bigint generated by default as identity primary key,
  request_id bigint not null references public.interest_requests(id) on delete cascade,
  product_id bigint not null references public.products(id),
  quantity integer not null default 1 check(quantity>0),
  unit_price_crc numeric(12,2),
  unit_price_usd numeric(12,2),
  discount_percentage real,
  boss_note text,
  product_snapshot jsonb not null default '{}'::jsonb,
  constraint uq_request_product unique(request_id,product_id)
);

-- Índices para optimizar consultas
create index if not exists idx_interest_items_request on public.interest_request_items(request_id);
create index if not exists idx_interest_items_product on public.interest_request_items(product_id);

-- Habilitar RLS (Row Level Security)
alter table public.interest_requests enable row level security;
alter table public.interest_request_items enable row level security;

-- Políticas de seguridad para usuarios anónimos y autenticados
-- Política para insertar solicitudes de interés (permite a todos los usuarios)
create policy if not exists "allow_insert_interest_requests"
on public.interest_requests for insert
with check(true);

-- Política para insertar items de solicitudes (permite a todos los usuarios)
create policy if not exists "allow_insert_interest_request_items"
on public.interest_request_items for insert
with check(exists(select 1 from public.interest_requests r where r.id=request_id));

-- Política para leer solicitudes (solo el propietario o admin)
create policy if not exists "allow_select_interest_requests"
on public.interest_requests for select
using(true);

-- Política para leer items de solicitudes
create policy if not exists "allow_select_interest_request_items"
on public.interest_request_items for select
using(true);

-- Vista optimizada para cards de productos
create or replace view public.product_card_view as
select
  p.id,
  coalesce(p.name_es,p.name) as name,
  p.description,
  p.category_id,
  p.sku,
  p.brand,
  p.dolar_price,
  p.discount_percentage,
  p.weight_kg, p.length_cm, p.width_cm, p.height_cm,
  (
    select elem->>'url'
    from jsonb_array_elements(p.media) elem
    where coalesce(elem->>'type','image')='image' or (elem ? 'url')
    limit 1
  ) as main_image_url
from public.products p
where p.is_active=true;